### ISSUE TITLE
10-20% message loss when using Stomp Output

### ISSUE THREAD

**Issue by SuperFunks** [logstash-plugins/logstash-output-stomp#16]
Hi there,

We are experiencing 10-20% message drop when sending messages from Logstash 5.2 to a Universal Messaging Queue with the STOMP protocol. (Also verified with Logstash 2.4)

**Config to reproduce:**

```
input {
        tcp {
                port => 5001
                type => "umrelay"
        }
}

output {
        file {
            path => "/tmp/stash.out"
        }
        if [type] == "umrelay" {
            stomp {
                 destination => "/test/testqueue"
                 host => "x.x.x.x"
                port => 17092
            }
        }
        stdout{}
}
```

e are using python to send 100.000 messages to the Logstash TCP input - and outs the messages to a file, stomp and console.

The file contains all 100.000 messages
The console writes all 100.000 messages
The Stomp output produces 83.560 messages

The loss happens at rates above 100 pr. second.

We have verified the STOMP functionality on UM by running 100.000 messages to it directly with Python - and all messages are persisted.
We have also tested multiple input path to logstash but we consistantly get everything written to file-out and console, but 10-20% is lost on the STOMP output.

**Operating System:**
Source: Debian
Target: OpenSuse

**Sample Data:**
The message sent from Python in all experiements is "i\n" where i is the current message number in an iteration of 100.000

**Steps to reproduce:**
Send messages to any logstash input at a message rate above 100 pr. second, and output on Stomp Output.
Count your input and output and assess the message drop. We see about 10-20% drop.

This is a problem :slight_smile: - And would like to see a fix to this :wink:

Best regards,

Mr.EoniX

**Comment by ph** [comment]
@consulthys Do you have any idea what could be causing this?

I am wondering if the library returns something or not at that line when it drops the message.
https://github.com/logstash-plugins/logstash-output-stomp/blob/master/lib/logstash/outputs/stomp.rb#L86

**Comment by consulthys** [comment]
That's an interesting issue and looks a lot like issue #8 I filed a while ago. Ultimately, the issue was that the plugin was not disconnecting properly, and hence messages would be lost. @SuperFunks can you run logstash with `--debug` and share your logging output?

**Comment by SuperFunks** [comment]
Sure thing - the logfile proved to be pretty big though.

I ran a test of 1 million events - and we got 812165 events into the Queue.

Here is the log from the run:
[stomp-debug.zip](https://github.com/logstash-plugins/logstash-output-stomp/files/771053/stomp-debug.zip)

I have cleared it for sensitive information - but i hope you can still find out what might be wrong.

**Comment by ph** [comment]
I've looked at the debug log file:

1. I don't see any errors.
2. the plugins receive all the events `cat logstash-plain.log | grep stomp | grep events | grep -o '>\d\+' | grep -o '\d\+' | paste -sd+ - | bc` => 1000000

**Comment by ph** [comment]
> When passed a block, the transaction scope will automatically transmit a BEGIN frame, deliver all transactional frames in the block with a matching transaction header and then send a COMMIT frame to complete the transaction. If an error is raised within the block, an ABORT frame will be sent to the broker to roll-back the transaction and the offending error will be re-raised.

From the documentation if an error is done within the block we should have seen it?

**Comment by ph** [comment]
Another thing from the log, we connect to stomp once.

`[2017-02-13T13:26:15,848][DEBUG][logstash.outputs.stomp   ] Connected to stomp server`

**Comment by ph** [comment]
OH OH The `#close` method seems to never be called, I can't find trace of `Disconnecting from stomp broker` in the log.

@SuperFunks How are you stopping logstash? Are you waiting for a complete shutdown before doing the asserts on the stomp side?

The last line in the logs you have provided are the following, which indicate that LS was still in the process of shuttting down.

```
[2017-02-13T13:35:50,917][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
[2017-02-13T13:35:55,918][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
[2017-02-13T13:36:00,919][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
[2017-02-13T13:36:05,919][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
[2017-02-13T13:36:10,919][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
[2017-02-13T13:36:15,919][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
[2017-02-13T13:36:20,919][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
[2017-02-13T13:36:25,919][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
[2017-02-13T13:36:30,919][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
```

The disconnect line should happen after this, which mean that each worker threads didn't call `disconnect` on the stomp client and would drop the current inflight messages. Since this plugin uses the concurrency `legacy` model each worker has is own `buffer`

**Comment by ph** [comment]
I am not completely sure about the `#disconnect`, it's my current working theory. my definition of a transaction would be like a blocking call, either it complete or not. See https://github.com/iande/onstomp/blob/master/extra_doc/UserNarrative.md#transaction

But maybe it's not the case, since the library is async and they use callbacks for some of the error handling.

**Comment by SuperFunks** [comment]
Hi there,

I never shut down the logstash on this run. But waited 5 minutes before extracting the debuglog.

We have however done tests of this before where some part of the missing events get pushed to the queue but nowhere near the amount lost. Ill make another run with debug where we ask logstash to shutdown, so you can see the disconnects as well.

**Comment by ph** [comment]
@SuperFunks Thanks, we will figure it out!

The code sending events is pretty thin, https://github.com/logstash-plugins/logstash-output-stomp/blob/master/lib/logstash/outputs/stomp.rb#L77-L88, So I would think its either a problem with our usage of the stomp library or the library itself.

**Comment by consulthys** [comment]
@SuperFunks Thanks for the logs. In order to remove the noise, would it be possible for you to remove the `file` and `stdout` outputs and keep only the `stomp` one? Moreover, I think that 1000 entries should be sufficient to highlight the issue and keep the log smaller.

We might benefit from using the finer-grained [event callbacks](https://github.com/iande/onstomp/blob/master/extra_doc/UserNarrative.md#events-and-callbacks) in order to gain more insights into what's going on internally.

**Comment by SuperFunks** [comment]
This is a run for 10000 events - with only Stomp output activated - and the logstash instance is terminated at the end - and disconnects become visible in the log.

Out of 10000 events we got 8316 onto the Queue.

Here is the log: [stomp-debug2.zip](https://github.com/logstash-plugins/logstash-output-stomp/files/777095/stomp-debug2.zip)

I dont understand the "Event callbacks" or if that was meant for me.
Let me know if i can do anything else to help.

**Comment by consulthys** [comment]
Thanks @SuperFunks I'll have a look.

The mention to "event callbacks" was a note to myself to maybe add in the plugin in order to gain more insights into what's going on internally. Time permitting, I'll get into this.

**Comment by SuperFunks** [comment]
Looking at the log i see 10000 Filter events and 10000 Output events.
So it must be something happening inside the output events.

**Comment by consulthys** [comment]
Yes, agreed, something's fishy in the stomp output, not yet sure what it is, but we'll figure it out.

**Comment by ph** [comment]
Thanks @SuperFunks, @consulthys Yup, seems something in the library, Yesterday I took a look at the issues in the library repo but I didn't find anything that could be linked to this case. I am pretty sure we use the latest version of the gem since we don't any constraints set on the library.

IIRC, stomp uses another thread to send the events, I wonder the following:

- It there transaction size limit on stomp, are we at risk of pushing that limit that could make some events ignored on every batch send.
- Thread safety issue in the plugin?

Maybe we could try to just remove the transaction first.

**Comment by consulthys** [comment]
@ph @SuperFunks I've come up with a solution that seems to do the trick. Basically, we're now asking for a receipt for each SEND frame that we're sending and in the `close` function we'll suspend the execution of the thread as long as we don't get all receipts for all SEND frames.

=> See PR #17

**Comment by ph** [comment]
I am not sure if this will work as intended, the `onstomp` library advantages is to use an evented model and a background threads to send the messages. I believe this model still apply when we send a `transaction`.

So I think with the code from #17  will have threading issues, for the following reason:

- Multi receive is called in the **workers** thread
- `@done` is reset with the `events.size`
- @done is not a thread safe value
- The value of `@done` will or can be changed in the `onstomp` connection thread on a receipt callback.
- `#close` is called from another thread
- the value of `@done` won't cross the memory barrier, so it could be true but in reality, we are processing a batch.

Also, @superfunks lost events without shutting down Logstash, @consulthys did you reproduce the data loss without the receipts callbacks?

Also from my understanding, `#disconnect` will flush any pending event from the buffer to the broken see https://github.com/iande/onstomp/blob/01830aaec69641d5ce82ed315b7ba74c3937e02e/lib/onstomp/client.rb#L101

**Comment by consulthys** [comment]
Yeah, I sort of reproduced the issue, which is weird because I used to lose events before contributing #8 but never anymore after that.

I thought there wold be threading issues, but being a Ruby noob, I wasn't really sure where... Anyway...now this is probably a dumb question but is there a `volatile` (Java) equivalent in Ruby?

**Comment by consulthys** [comment]
And here's another interesting read about how the onstomp library handles asynchronous calls: https://github.com/iande/onstomp/wiki/Asynchronous
Using receipts seems the only way to go...

**Comment by ph** [comment]
@consulthys Ah thanks for the link to the doc! I've missed that one.

> Yeah, I sort of reproduced the issue, which is weird because I used to lose events before contributing #8 but never anymore after that.

Yup, not sure what would cause this, networks or the nature of the event loop in the library.

After reading the doc I think your idea is what we need to do in that case! But instead of having a global `@done` we might need a done per batch? So in the **close** we check that we don't have any batch `inflight` ? Does a transaction has a concept of receipts?

```ruby
finished_processing = false
client = OnStomp.connect 'stomp://localhost'

client.send('/topic/test', 'Hello World!') do |r|
  puts "Got a receipt for Hello World!"
  finished_processing = true
end

client.send '/queue/test', 'Hello Subscriber!'

Thread.pass until finished_processing

client.disconnect
exit
```

Also until everything is stabilized we should probably add the hooks for more logging.

```ruby
client.on_receipt do |r, *_|
end

client.on_error do |e, *_|
end
```

For the thread safety, you can either use the Java classes directly or the [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby) library.

**Comment by SuperFunks** [comment]
Hi guys,

Very interesting findings indeed - let me know if there is anything you need me to test out.

**Comment by consulthys** [comment]
@ph I agree this is how we should do it, however, we need to set `finished_processing` only when the full transaction is done and all SEND frames have been "receipted". 

To my knowledge, there is no receipt for a transaction since a transaction is an abstraction implemented by the `BEGIN`, `COMMIT` and `ABORT` frames, i.e. there is no `TRANSACTION` frame per se. 

So the only way I see this could be done is that each time `multi_receive` is called we need to track how many events we send (`=events.length`) and how many receipts we get and call it done when the number of receipts matches the number of events. That's how I came up with my implementation, but since I'm still learning Ruby's threading model, I might have missed a few points, like the ones you pointed at. 

The difficulty lies in the fact that the thread executing `multi_receive` and the thread executing the receipt callbacks for each event are not the same, so since we need to compare two values from two different threads, we basically need to scope this computation local to the `multi_receive` function, yet somehow give an "hint" at the instance level that the current batch could be sent so that the close method can do its job, too. I'll research some more how we could achieve this.

**Comment by ph** [comment]
> @ph I agree this is how we should do it, however, we need to set finished_processing only when the full transaction is done and all SEND frames have been "receipted".

Agree.

> To my knowledge, there is no receipt for a transaction since a transaction is an abstraction implemented by the BEGIN, COMMIT and ABORT frames, i.e. there is no TRANSACTION frame per se.

Yeah, It their implementation is still vague. https://stomp.github.io/stomp-specification-1.1.html

> The difficulty lies in the fact that the thread executing multi_receive and the thread executing the receipt callbacks for each event are not the same, so since we need to compare two values from two different threads, we basically need to scope this computation local to the multi_receive function, yet somehow give an "hint" at the instance level that the current batch could be sent so that the close method can do its job, too. I'll research some more how we could achieve this.

Maybe it's time to take a step back, the current implementation complexity is coming from the fact that the library we currently used is using an async idiom. The thing is logstash has already a workers model to help performance issues in a blocking output. 

I am wondering if in this case, if it would be much easier to use a blocking library instead of the async one. Like this one https://github.com/stompgem/stomp, the problem with the async library is applying back pressure up to the producer is much harder.

**Comment by ph** [comment]
> the problem with the async library is applying back pressure up to the producer is much harder.

I should have said, everything is much harder to track

**Comment by consulthys** [comment]
Using a blocking library would make perfect sense in my opinion, too. 👍

**Comment by consulthys** [comment]
@ph do you want me to venture into it, or will you handle it?

**Comment by ph** [comment]
@consulthys If you want to tackle, go ahead :)

**Comment by ph** [comment]
I've tried to find why we are using `onstomp`, but I haven't found any good reason, https://github.com/elastic/logstash/pull/56

Another thing, if we go this route we can make the output use the `concurrency :shared` since it will be stateless.

**Comment by consulthys** [comment]
Thanks @ph, I'll tackle another iteration with this new strategy in my existing PR. I'll keep you guys posted once I have something working.

**Comment by consulthys** [comment]
I've pushed another iteration using the synchronous stomp library. It seems to work ok with my local configuration. 

@SuperFunks if you want to try this out and see if this solves your problem, you can do the following:

```
> cd ~
> git clone https://github.com/consulthys/logstash-output-stomp.git
> cd logstash-output-stomp
> gem build logstash-output-stomp.gemspec  
> $LOGSTASH_HOME/bin/logstash-plugin install ~/logstash-output-stomp/logstash-output-stomp-3.0.5.gem
```
Then run logstash as usual and see how it goes

**Comment by SuperFunks** [comment]
Hi there @consulthys !
We just tested out the fix attempt - and we now get 100% of the events pushed to the queue! Hurray! - But the logstash crashes upon completion - and we get the following error messages:

```
/etc/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/server.rb:322:in `handle_servers'
/etc/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/server.rb:296:in `run'
[2017-02-21T11:02:50,016][DEBUG][logstash.agent           ] 2017-02-21 11:02:50 +0100: Listen loop error: #<Errno::EBADF: Bad file descriptor - Bad file descriptor>
[2017-02-21T11:02:50,016][DEBUG][logstash.agent           ] org/jruby/RubyIO.java:3705:in `select'
/etc/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/server.rb:322:in `handle_servers'
/etc/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/server.rb:296:in `run'
```


Also we are seeing this:

`[2017-02-22T10:55:16,980][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<Stomp::Error::NilMessageError: Stomp::Error::NilMessageError>, :backtrace=>["/etc/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/stomp-1.4.3/lib/client/utils.rb:193:in `start_listeners'", "org/jruby/RubyKernel.java:1479:in `loop'", "/etc/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/stomp-1.4.3/lib/client/utils.rb:189:in `start_listeners'"]}
`

**Comment by consulthys** [comment]
Thanks for the feedback @SuperFunks It looks very much like [this issue](https://github.com/stompgem/stomp/issues/109), which points at the fact that this error occurs if the connection is not configured as reliable. I've applied the fix and pushed, you may try again.

Regarding the "Bad file descriptor" issue it looks like this is another issue in the embedded Puma web server, not sure how to fix it. Maybe @ph has an idea ?

**Comment by SuperFunks** [comment]
Jo @consulthys - I just updated the gem, but now the logstash never starts the pipeline ? - It gets stuck during startup. Could that be something from your latest fix?

**Comment by consulthys** [comment]
Sorry about that, please check it out again.

**Comment by SuperFunks** [comment]
Pipeline started now :) - testing some more

**Comment by SuperFunks** [comment]
Seems the connection is kept and logstash stays alive - but i get this message in the log:

```
on_miscerr
{:connect_headers=>{}, :reliable=>true, :initial_reconnect_delay=>0.01, :max_reconnect_delay=>30.0, :use_exponential_back_off=>true, :back_off_multiplier=>2, :max_reconnect_attempts=>0, :randomize=>false, :connect_timeout=>0, :parse_timeout=>5, :dmh=>false, :closed_check=>true, :hbser=>false, :stompconn=>false, :max_hbread_fails=>0, :max_hbrlck_fails=>0, :fast_hbs_adjust=>0.0, :connread_timeout=>0, :tcp_nodelay=>true, :start_timeout=>0, :sslctx_newparm=>nil, :ssl_post_conn_check=>true, :hosts=>[{:login=>"", :passcode=>"", :host=>"dkaint-uc0c01.corp.lego.com", :port=>17092}], :logger=>#<Stomp::NullLogger:0x51484b6a>, :cur_host=>"dkaint-uc0c01.corp.lego.com", :cur_port=>17092, :cur_login=>"", :cur_passcode=>"", :cur_ssl=>nil, :cur_recondelay=>30.0, :cur_parseto=>5, :cur_conattempts=>0, :cur_failure=>nil, :openstat=>true}
es_recv: connection.receive returning EOF as nil - resetting connection.

```

**Comment by SuperFunks** [comment]
The lastest update has really bad performance somehow. - We did 32K EPS to the UM without issues - but now it seems we cannot get throughput higher than 4K and seems the rate drops many times to 0.

**Comment by SuperFunks** [comment]
Shows before and after the latest update:

![image](https://cloud.githubusercontent.com/assets/20201219/23209259/d6958322-f8f8-11e6-8547-18ed540e4d21.png)

**Comment by SuperFunks** [comment]
Also Logstash cant stop now:

```
[2017-02-22T12:33:41,245][WARN ][logstash.runner          ] Received shutdown signal, but pipeline is still waiting for in-flight events
to be processed. Sending another ^C will force quit Logstash, but this may cause
data loss.
[2017-02-22T12:33:41,332][WARN ][logstash.shutdownwatcher ] {}
[2017-02-22T12:33:41,333][ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2017-02-22T12:33:46,332][WARN ][logstash.shutdownwatcher ] {}
[2017-02-22T12:33:51,323][WARN ][logstash.shutdownwatcher ] {}
[2017-02-22T12:33:56,321][WARN ][logstash.shutdownwatcher ] {}
[2017-02-22T12:34:01,314][WARN ][logstash.shutdownwatcher ] {}
[2017-02-22T12:34:06,314][WARN ][logstash.shutdownwatcher ] {}
[2017-02-22T12:34:06,315][ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2017-02-22T12:34:11,311][WARN ][logstash.shutdownwatcher ] {}

```

**Comment by consulthys** [comment]
Indeed, this isn't looking very good. I've fixed the fact that Logstash could not stop anymore, this was due to a setting that would try to reconnect indefinitely upon closing the connection. 

However, I guess that the difference in throughput is due to the fact that we're now using a fully synchronous library. Have you tried playing with higher `-w` settings?

**Comment by SuperFunks** [comment]
The first gem i updated which had the crashing at the end of the batch was fast - very fast.
The latest gem which couldnt get throughput up, looked like it lost its rate because it got hard disconnected many times.
We have been running with -w 60 throughout the tests - so im hoping the fixed reconnection thing also fixes the loss in rate.

Let me know when i can make another pull and test.

**Comment by consulthys** [comment]
You can go ahead and try

**Comment by SuperFunks** [comment]
Logstash can now start and stop - and performance is back to normal - 10000+ pr. second on a single node.

I will try to put some more pressure on it now.

**Comment by ph** [comment]
@SuperFunks @consulthys Hello, just woke up.

Indeed since we are now using a synchronous library, it will be directly affected by your number of Logstash workers. 

I do not know all the details of the onstomp library, but they probably have a poll of threads. So when you were testing with the previous version with `-w 60` you probably had more hidden workers doing the work, since the pool was not shared between Logstash workers.

But not losing events  is more important, also this change to sync library will make sure that the back pressure is correctly applied back to the inputs and will make it behave correctly with the persistent queue present in 5.2+

Let's make sure we pin the version to be higher than 1.4.3, from the [changelog](https://github.com/stompgem/stomp/blob/dev/CHANGELOG.md#143-20160821) 1.4.2 had a memory leak.

```Gem version 1.4.3. Fix broken install. Do not try to install 1.4.2.```



@consulthys Thanks for the works! 👍

**Comment by consulthys** [comment]
@ph I've pinned the dependency to `>= 1.4.3`

**Comment by ph** [comment]
@consulthys  I think we should be more conservative and use `~> 1.4.3` notation, this will allow us to pick up patch level but not get breakings changes.

**Comment by SuperFunks** [comment]
Im still getting spammed with this message when the pipe is idle:

```
on_miscerr
{:connect_headers=>{}, :reliable=>true, :initial_reconnect_delay=>0.01, :max_reconnect_delay=>30.0, :use_exponential_back_off=>true, :back_off_multiplier=>2, :max_reconnect_attempts=>3, :randomize=>false, :connect_timeout=>0, :parse_timeout=>5, :dmh=>false, :closed_check=>true, :hbser=>false, :stompconn=>false, :max_hbread_fails=>0, :max_hbrlck_fails=>0, :fast_hbs_adjust=>0.0, :connread_timeout=>0, :tcp_nodelay=>true, :start_timeout=>0, :sslctx_newparm=>nil, :ssl_post_conn_check=>true, :hosts=>[{:login=>"", :passcode=>"", :host=>"dkaint-uc0c01.corp.lego.com", :port=>17092}], :logger=>#<Stomp::NullLogger:0x73984d16>, :cur_host=>"dkaint-uc0c01.corp.lego.com", :cur_port=>17092, :cur_login=>"", :cur_passcode=>"", :cur_ssl=>nil, :cur_recondelay=>0.01, :cur_parseto=>5, :cur_conattempts=>0, :cur_failure=>nil, :openstat=>true}
es_recv: connection.receive returning EOF as nil - resetting connection.
```

**Comment by consulthys** [comment]
This happens [here](https://github.com/stompgem/stomp/blob/42cda45a6e3e90e4677a152e7353bb36017d7a60/lib/stomp/connection.rb#L481-L485), I'll investigate how to avoid this.

**Comment by consulthys** [comment]
@SuperFunks what kind of broker do you have behind the scenes? Is that ActiveMQ?

**Comment by consulthys** [comment]
It seems this error is mostly "spam" and gets printed when the connection fails, reconnects and fails again ([source](http://activemq.2283324.n4.nabble.com/fix-for-dirty-part-receive-fixed-td2398402.html)). I'm leaning towards swallowing this thing or setting a lower debug level to hide it somehow...

**Comment by SuperFunks** [comment]
Atleast something which wont fill up the local disk of the logstash node :)
The broker used is a [Universal Messaging Queue](http://terracotta.org/products/universal-messaging) with Stomp support enabled.

**Comment by SuperFunks** [comment]
Another thing perhaps a little out of scope is that logstash crashes if the broker becomes unavailable:

```
[2017-02-22T17:28:59,952][ERROR][logstash.inputs.tcp      ] An error occurred. Closing connection {:client=>"0:0:0:0:0:0:0:1:39947", :exception=>#<Errno::EBADF: Bad file descriptor - Bad file descriptor>, :backtrace=>["org/jruby/RubyIO.java:3019:in `sysread'", "/etc/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:240:in `read'", "/etc/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:164:in `handle_socket'", "/etc/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:153:in `server_connection_thread'"]}
[2017-02-22T17:28:59,957][ERROR][logstash.outputs.stomp   ] Error while sending 18 events in transaction tx-12225754851102349410 {:error=>#<Stomp::Error::NoCurrentConnection: Stomp::Error::NoCurrentConnection>}
[2017-02-22T17:28:59,965][ERROR][logstash.outputs.stomp   ] Error while sending 1 events in transaction tx-7287439439705156272 {:error=>#<Stomp::Error::NoCurrentConnection: Stomp::Error::NoCurrentConnection>}
[2017-02-22T17:28:59,969][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Tcp port=>5001, type=>"umrelay", id=>"6a087949d7244823cecd9a7db004967e7279c266-1", enable_metric=>true, codec=><LogStash::Codecs::Line id=>"line_2cb989f7-1319-4f2e-a930-0b73ab0d6a10", enable_metric=>true, charset=>"UTF-8", delimiter=>"\n">, host=>"0.0.0.0", data_timeout=>-1, mode=>"server", proxy_protocol=>false, ssl_enable=>false, ssl_verify=>true, ssl_key_passphrase=><password>>
  Error: Bad file descriptor - Bad file descriptor
```

**Comment by consulthys** [comment]
Seems more related to the `tcp` input than the `stomp` output right?

**Comment by SuperFunks** [comment]
Ah - correct - the unrecoverable error is in the tcp plugin.
We will have to setup some redundancy and upkeep scripts to ensure logstash survives/recovers.

**Comment by consulthys** [comment]
I still don't think logstash should crash because of that. The `tcp` input plugin should probably handle this more gracefully, so it might still be worth creating an issue for it

**Comment by consulthys** [comment]
@SuperFunks I've added a custom logger that will make everything much more quiet unless you start logstash with `--debug`. Please try it out and let us know.

**Comment by ph** [comment]
@SuperFunks Did the PR fixed your issue?

**Comment by SuperFunks** [comment]
Hi again,
After some testing we have the following conclusion:

- Events are now safely delivered - and performance is good. (Yay!)
- The plugin makes logstash crash alot - so we should look into some mechanisms to prevent this.

Crashing Details:
We see it when ever the Broker is unavailable either if the queue is being cleared or the endpoint is down.

We are currently running version 2.4.1 - because the RELP input plugin for Logstash currently cannot compile for version 5.x

Both version 2.4.1 and 5.x crash as soon as the broker is down or is doing internal operations.

**Comment by consulthys** [comment]
Thanks for the feedback @SuperFunks so basically 2 steps forward and 1 backward. Are you still getting the same error as previously, i.e. `Error: Bad file descriptor - Bad file descriptor` ?

**Comment by ph** [comment]
@SuperFunks are you still experiencing the above issue?

**Comment by SuperFunks** [comment]
We are currently upgrading to logstash 5.2 as the RELP-Input now seem to compile.
We actually havent seen the crashing happening ever since we updated our license on our UM queue (broker) - they might have had a very weird way of shutting of Logstash on the expired license we were running with.

When upgraded to 5.2 - i will report back after 7 days of runtime.

**Comment by ph** [comment]
@SuperFunks Keep us in the loop!

**Comment by SuperFunks** [comment]
We have now succesfully set the pipeline up with Logstash 5.2.2 and the latest STOMP output module.
After a while we get this error:

**Logstash node 1:**
[2017-03-29T13:30:46,738][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<Stomp::Error::BrokerException: Stomp::Error::BrokerException>, :backtrace=>["org/jruby/RubyThread.java:696:in `join'", "org/jruby/RubyArray.java:1613:in `each'", "/etc/logstash-5.2.2/logstash-core/lib/logstash/pipeline.rb:421:in `wait_inputs'", "/etc/logstash-5.2.2/logstash-core/lib/logstash/pipeline.rb:241:in `run'", "/etc/logstash-5.2.2/logstash-core/lib/logstash/agent.rb:387:in `start_pipeline'"]}
[2017-03-29T13:30:46,901][ERROR][logstash.outputs.stomp   ] Error while sending 125 events in transaction tx-9912728657677814079 {:error=>#<Stomp::Error::NoCurrentConnection: Stomp::Error::NoCurrentConnection>}

**Logstash node 2:**
[2017-03-29T13:30:53,482][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<Stomp::Error::BrokerException: Stomp::Error::BrokerException>, :backtrace=>["org/jruby/RubyThread.java:696:in `join'", "org/jruby/RubyArray.java:1613:in `each'", "/etc/logstash-5.2.2/logstash-core/lib/logstash/pipeline.rb:421:in `wait_inputs'", "/etc/logstash-5.2.2/logstash-core/lib/logstash/pipeline.rb:241:in `run'", "/etc/logstash-5.2.2/logstash-core/lib/logstash/agent.rb:387:in `start_pipeline'"]}


This might be duo to some wierdness with our Universal Messaging Queue - but it is a stomp broker - and i guess we dont want the Logstash to crash because of an error like that.

**Comment by ph** [comment]
I think we should retry forever on exception until the [DLQ](https://github.com/elastic/logstash/issues/6700) in logstash land, https://github.com/logstash-plugins/logstash-output-stomp/pull/17/files#diff-8a81de0d9fff69208abe4d985dcf6f72R89 we should have a retry in the rescue block.

Also I think the `Stomp::Error::BrokerException` might not inherits from `Exception` and making the rescue fails?
